### ISSUE TITLE
Release 0.13.0b Error in template path:  Template 'projects/base_project.html' not found

### ISSUE THREAD

**Issue by PavelStepashkin** [lmsecure/Setezor#14]
Original setezor/app_routes/pages/project.py line 46
"return aiohttp_jinja2.render_template('projects/base_project.html', request=request, context=context)"
After my corrections it works well:
"return aiohttp_jinja2.render_template('projects.html', request=request, context=context)"

**Comment by lmsecure** [comment]
> Original setezor/app_routes/pages/project.py line 46 "return aiohttp_jinja2.render_template('projects/base_project.html', request=request, context=context)" After my corrections it works well: "return aiohttp_jinja2.render_template('projects.html', request=request, context=context)"

Dear Pavel Stepashkin, thank you for your interest in our project! We have found out the cause of the problem and already fixed it.
