### ISSUE TITLE
ERROR: deprecated use case

### ISSUE THREAD

**Issue by szybnev** [lmsecure/Setezor#9]
/home/ubu/LMS.NetMap/database/queries_files/base_queries.py:263: SAWarning: Evaluating non-mapped column expression 'tasks.id' onto ORM instances; this is a deprecated use case.  Please make use of the actual mapped columns in ORM-evaluated UPDATE / DELETE expressions.

Ошибка возникла при ручном обновлении вкладки Task.

**Comment by lmsecure** [comment]
ручное редактирование тасков запретили. переход на SQLAlchemy 2.X запланирован и будет осуществлен стабильном релизе версии 1.X
